/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2024-10-16 16:03:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class Ulogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/navbar.html", Long.valueOf(1729094253464L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write(" <title>USER LOGIN</title>\r\n");
      out.write("        <style>\r\n");
      out.write("            *{\r\n");
      out.write("                margin: 0;\r\n");
      out.write("                padding: 0;\r\n");
      out.write("            }\r\n");
      out.write("            body{\r\n");
      out.write("                background-color:  white;\r\n");
      out.write("            }\r\n");
      out.write("            .icl nav{\r\n");
      out.write("                background-color: #312e2c;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .all{\r\n");
      out.write("                padding:3rem 8rem;\r\n");
      out.write("                display: flex;\r\n");
      out.write("                /*flex-direction: column;*/\r\n");
      out.write("                justify-content: center;\r\n");
      out.write("                align-items: center;\r\n");
      out.write("            }\r\n");
      out.write("            .box1{\r\n");
      out.write("                flex: 1;\r\n");
      out.write("            }\r\n");
      out.write("            .box1 img{\r\n");
      out.write("                width:  25rem;\r\n");
      out.write("                height: 20rem;\r\n");
      out.write("\r\n");
      out.write("            }\r\n");
      out.write("            .box2{\r\n");
      out.write("                flex: 1;\r\n");
      out.write("                display: flex;\r\n");
      out.write("                background-color:  #312e2c;\r\n");
      out.write("                border: 5px solid #d49831;\r\n");
      out.write("                color: white;\r\n");
      out.write("                height:20rem;\r\n");
      out.write("                width: 40rem;\r\n");
      out.write("                padding: 3rem;\r\n");
      out.write("                font-size: x-large;\r\n");
      out.write("                border-radius: 2rem;\r\n");
      out.write("                box-shadow: 7px 7px 18px 1px grey;\r\n");
      out.write("            }\r\n");
      out.write("            table{\r\n");
      out.write("                height:90%;\r\n");
      out.write("                /*border: 2px solid black;*/\r\n");
      out.write("                width: 20em;\r\n");
      out.write("            }\r\n");
      out.write("            input[type=\"text\"],[type=\"password\"]{\r\n");
      out.write("                height: 30px;\r\n");
      out.write("                width: 300px;\r\n");
      out.write("                background: transparent;\r\n");
      out.write("                border: none;\r\n");
      out.write("                border-bottom: 3px solid black;\r\n");
      out.write("                outline: none;\r\n");
      out.write("                color: white;\r\n");
      out.write("                font-weight: bold;\r\n");
      out.write("                font-style: italic;\r\n");
      out.write("                padding: 0 1rem 0 1rem;\r\n");
      out.write("            }\r\n");
      out.write("            .btn{\r\n");
      out.write("                height: 35px;\r\n");
      out.write("                width: 110px;\r\n");
      out.write("                background-color: #d49831;\r\n");
      out.write("                border-radius: 30px;\r\n");
      out.write("                margin: 10px 20px 0 0;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .fg{\r\n");
      out.write("                text-decoration: none;\r\n");
      out.write("                color: #d49831;\r\n");
      out.write("                font-size: large;\r\n");
      out.write("            }\r\n");
      out.write("            table tr td{\r\n");
      out.write("                text-align: center;\r\n");
      out.write("            }\r\n");
      out.write("            table tr{\r\n");
      out.write("\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            @media screen and (max-width:768px){\r\n");
      out.write("\r\n");
      out.write("                .box2{\r\n");
      out.write("                    flex-direction: column;\r\n");
      out.write("                    height:fit-content;\r\n");
      out.write("                    width: 20rem;\r\n");
      out.write("\r\n");
      out.write("                }\r\n");
      out.write("                input[type=\"text\"],[type=\"password\"]{\r\n");
      out.write("                    height: 30px;\r\n");
      out.write("                    width: 15rem;\r\n");
      out.write("                }\r\n");
      out.write("                table{\r\n");
      out.write("                    height: 15rem;\r\n");
      out.write("                    width: 20rem;\r\n");
      out.write("                }\r\n");
      out.write("                .box1 img{\r\n");
      out.write("                    width:  20rem;\r\n");
      out.write("                    height: 15rem\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("        </style>\r\n");
      out.write("\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("        <div class=\"icl\">\r\n");
      out.write("            ");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("            *{\r\n");
      out.write("                margin: 0;\r\n");
      out.write("                padding: 0;\r\n");
      out.write("            }\r\n");
      out.write("            nav{\r\n");
      out.write("                height: 10vh;\r\n");
      out.write("                /*border-bottom: 2px solid maroon;*/\r\n");
      out.write("                display: flex;\r\n");
      out.write("                flex-direction: row;\r\n");
      out.write("                justify-content: space-between;\r\n");
      out.write("                /*border: 2px solid black;*/\r\n");
      out.write("                /*box-shadow: 1px 2px 15px 1px grey;*/\r\n");
      out.write("                font-size: 1.5rem ;\r\n");
      out.write("                /*font-weight: bolder;*/\r\n");
      out.write("            }\r\n");
      out.write("            ul{\r\n");
      out.write("               display: flex;\r\n");
      out.write("               /*justify-content: center;*/\r\n");
      out.write("               align-items: center;\r\n");
      out.write("\r\n");
      out.write("            }\r\n");
      out.write("            li{\r\n");
      out.write("                display:inline-block;\r\n");
      out.write("            }\r\n");
      out.write("            nav a{\r\n");
      out.write("               color: white;\r\n");
      out.write("                /*-webkit-text-stroke-width: 1px;*/\r\n");
      out.write("                /*-webkit-text-stroke-color: black ;*/\r\n");
      out.write("                margin: 10px;\r\n");
      out.write("                text-decoration: none;\r\n");
      out.write("                list-style: none;\r\n");
      out.write("            }\r\n");
      out.write("           \r\n");
      out.write("            .logo h1 a{\r\n");
      out.write("                color: #d49831;\r\n");
      out.write("            }\r\n");
      out.write("            .logo{\r\n");
      out.write("                padding-left: 1rem;\r\n");
      out.write("                color: #d49831  ;\r\n");
      out.write("            }\r\n");
      out.write("            li a:hover{\r\n");
      out.write("                border-bottom: 5px solid #d49831;\r\n");
      out.write("                \r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            @media (max-width:768px){\r\n");
      out.write("                p{\r\n");
      out.write("                    font-size: 30px;\r\n");
      out.write("                    /*background-color: black;*/\r\n");
      out.write("                    margin: 2em 0 1em 10%;\r\n");
      out.write("                }\r\n");
      out.write("                ul li{\r\n");
      out.write("                    font-size: 1rem;\r\n");
      out.write("                }\r\n");
      out.write("                img{\r\n");
      out.write("                    height:1.9em;\r\n");
      out.write("                    width:3em;\r\n");
      out.write("                }\r\n");
      out.write("                ul{\r\n");
      out.write("                    flex-direction: column;\r\n");
      out.write("                    border: 2px solid yellow;\r\n");
      out.write("                   \r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </style>\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("         <nav>\r\n");
      out.write("                    <div class=\"logo\">\r\n");
      out.write("                        <h1><a href=\"index.jsp\" style=\"hover:none\">Book-Store</a></h1>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"home.jsp\">HOME</a></li>\r\n");
      out.write("                        <li><a href=\"Ulogin.jsp\">LOGIN</a></li>\r\n");
      out.write("                        <li><a href=\"Registration.jsp\">SIGNUP</a></li>\r\n");
      out.write("                        <li><a href=\"userHomepage.jsp\">PROFILE</a></li>\r\n");
      out.write("                        <li><a href=\"contact.jsp\">CONTACT US</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </nav>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("            <h1>\r\n");
      out.write("                ");

                                String registration = request.getParameter("register");
                                if (registration != null && registration.equals("success")) {
                                
      out.write("\r\n");
      out.write("                                <span style=\"color:green; font-size: medium ; text-align: center\">Registration Successfull</span>\r\n");
      out.write("                                ");

                                    }
                                
      out.write("\r\n");
      out.write("            </h1>\r\n");
      out.write("        <div class='all'>\r\n");
      out.write("            <div class=\"box2\">\r\n");
      out.write("                <div class=\"box1\">\r\n");
      out.write("                    <img src=\"image/log-in.png\" alt=\"not found\"/>\r\n");
      out.write("                </div>\r\n");
      out.write("                <form action=\"userLogin\" method=\"post\">\r\n");
      out.write("                    <table>\r\n");
      out.write("                        <h1 style=\"text-align:center\">LOGIN</h1>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td colspan=\"2\"> ");

                                String invi = request.getParameter("pass");
                                if (invi != null && invi.equals("incorrect")) {
                                
      out.write("\r\n");
      out.write("                                <span style=\"color:red; font-size: medium ; text-align: center\">**Username or Password incorrect..</span>\r\n");
      out.write("                                ");

                                    }
                                
      out.write("</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>Username:</td>\r\n");
      out.write("                            <td><input type=\"text\" name=\"uname\" required/></td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>Password:</td>\r\n");
      out.write("                            <td><input type=\"password\" name=\"password\" required/></td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("\r\n");
      out.write("                        <!--                        <tr>\r\n");
      out.write("                                                    <td colspan=\"2\"><input type=\"checkbox\">Remember me</td>\r\n");
      out.write("                                                </tr>-->\r\n");
      out.write("                        <tr style=\"text-align:center\">\r\n");
      out.write("                            <td colspan=\"2\"><input type=\"submit\" value=\"Submit\" class=\"btn\"/><input type=\"reset\" value=\"Reset\" class=\"btn\" /></td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td><p><a href=\"forgotPass.jsp\" class=\"fg\">Forgot Password?</a></p></td>\r\n");
      out.write("                            <td ><p>If new user? <a href=\"Registration.jsp\" class=\"fg\">SignUp</a></p></td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("\r\n");
      out.write("                    </table>\r\n");
      out.write("\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
